name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: icepuma/rust-action@1.43.0
      with:
        args: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test
